
version: '3.2'
services:
  postgres:
    image: postgres:latest
    restart: "no"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

    networks:
      - jobnet
    
  backend:
    image: job-assistant:latest
    restart: "no"
    platform: linux/amd64
    ports:
      - 8080:8000
    networks:
      - jobnet


networks:
  jobnet:
    ipam:
      config:
        - subnet: 192.168.119.0/24